### ISSUE TITLE
Live stream

### ISSUE THREAD

**Issue by benbro** [72lions/PlayingChunkedMP3-WebAudioAPI#1]
Is it possible to modify the code to support a live stream instead of a file?
In a live stream, we won't need to keep buffers after they were played and decode everything on each incoming frame.

I tried to decode and play each buffer separately with a new audioSource instead of appending everything to a single buffer but I have timing issues. Sometimes new chunks are cut or plays too fast.

Can you please explain the following?
- Why there are single digit milliseconds overlaps and how scheduledTime helps?
- Why do you add 0.010 to current time and decrease 0.05 from start time?
  https://github.com/72lions/PlayingChunkedMP3-WebAudioAPI/blob/master/mp3chunksplayer.js#L141
  https://github.com/72lions/PlayingChunkedMP3-WebAudioAPI/blob/master/mp3chunksplayer.js#L151
  https://github.com/72lions/PlayingChunkedMP3-WebAudioAPI/blob/master/mp3chunksplayer.js#L152

**Comment by 72lions** [comment]
Hey, no plans on supporting Live Stream. Sorry, but it was just an experiment. 
Concerning your questions:
- The scheduledTime and the 0.010 addition add a bit of overlap so that I'm sure that there is not going to be any empty space between the chunks.

**Comment by benbro** [comment]
thanks

**Comment by YurySolovyov** [comment]
@72lions is it possible to just append or enqueue some data so it can "just work" by continuously playing new data, without using overlap?

I'm not sure people can actually hear the overlap, but does not seem like a 100% clear solution (thanks for sharing it though).

**Comment by 72lions** [comment]
I don't know if it's possible with the Web Audio API but you can do it with EME https://github.com/72lions/PlayingChunkedMP3MediaSourceAPI

**Comment by 72lions** [comment]
I meant MSE

**Comment by kojilab** [comment]
I concur. I did some experiments with MSE and it works beautifully.  This is the article I used initially https://developers.google.com/web/updates/2015/06/Media-Source-Extensions-for-Audio#introduction
